export const MOCKED_REVIEWS = [
  // == Reviews for Listing 101 (10 Reviews) ==
  {
    id: 1001,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview: "Amazing place! Clean, great location, and wonderful host.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
    ],
    submittedAt: "2024-10-15T10:30:00Z",
    guestName: "Alex Johnson",
  },
  {
    id: 1002,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2005, // Bookingcom
    rating: 9,
    publicReview: "We loved our stay. The apartment was perfect for our trip.",
    submittedAt: "2024-10-12T14:22:00Z",
    guestName: "Sam Smith",
  },
  {
    id: 1003,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2022, // Google
    rating: 10,
    publicReview: "Highly recommend. Everything was as described. A+",
    reviewCategory: [{ category: "cleanliness", rating: 10 }],
    submittedAt: "2024-10-11T19:05:00Z",
    guestName: "Casey Brown",
  },
  {
    id: 1004,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview: "A beautiful apartment in a fantastic location. 10/10.",
    submittedAt: "2024-10-09T09:15:00Z",
    guestName: "Jordan Lee",
  },
  {
    id: 1005,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2000, // Direct
    rating: 9,
    publicReview: "Cozy, clean, and comfortable. Couldn't ask for more.",
    submittedAt: "2024-10-08T11:00:00Z",
    guestName: "Morgan White",
  },
  {
    id: 1006,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview: "Perfect stay.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
    ],
    submittedAt: "2024-10-05T16:45:00Z",
    guestName: "Taylor Davis",
  },
  {
    id: 1007,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2005, // Bookingcom
    rating: 8,
    publicReview:
      "It was okay. The location was great, but the street was a bit noisy at night.",
    submittedAt: "2024-10-02T20:00:00Z",
    guestName: "Chris Miller",
  },
  {
    id: 1008,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2022, // Google
    rating: 10,
    publicReview: "Fantastic view and very clean.",
    submittedAt: "2024-09-30T13:10:00Z",
    guestName: "Pat Wilson",
  },
  {
    id: 1009,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    submittedAt: "2024-09-28T18:00:00Z",
    guestName: "Dana Moore",
  },
  {
    id: 1010,
    listingMapId: 101,
    listingName: "Modern Downtown Loft (Austin)",
    type: "guest-to-host",
    status: "published",
    channelId: 2002, // Homeaway
    rating: 10,
    publicReview: "Will definitely be back!",
    reviewCategory: [{ category: "cleanliness", rating: 10 }],
    submittedAt: "2024-09-25T12:00:00Z",
    guestName: "Jessie Clark",
  },

  // == Reviews for Listing 102 (15 Reviews) ==
  {
    id: 1011,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    publicReview: "Great location, very small but perfect for one person.",
    submittedAt: "2024-10-20T11:00:00Z",
    guestName: "Alex Johnson",
  },
  {
    id: 1012,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2005, // Bookingcom
    rating: 8,
    publicReview: "Good value for the price. Location is unbeatable.",
    submittedAt: "2024-10-19T15:30:00Z",
    guestName: "Sam Smith",
  },
  {
    id: 1013,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview: "Loved it! So cozy and had everything I needed.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
    ],
    submittedAt: "2024-10-18T10:00:00Z",
    guestName: "Casey Brown",
  },
  {
    id: 1014,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2022, // Google
    rating: 9,
    publicReview:
      "A bit loud, but that's expected for downtown. Very convenient.",
    submittedAt: "2024-10-17T12:00:00Z",
    guestName: "Jordan Lee",
  },
  {
    id: 1015,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2007, // Expedia
    rating: 7,
    publicReview: "The key pickup was confusing. The room itself was fine.",
    submittedAt: "2024-10-15T19:00:00Z",
    guestName: "Morgan White",
  },
  {
    id: 1016,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    submittedAt: "2024-10-14T14:20:00Z",
    guestName: "Taylor Davis",
  },
  {
    id: 1017,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview: "Perfect spot for exploring the market.",
    submittedAt: "2024-10-12T11:30:00Z",
    guestName: "Chris Miller",
  },
  {
    id: 1018,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2005, // Bookingcom
    rating: 8,
    publicReview: "Clean and practical.",
    submittedAt: "2024-10-10T09:00:00Z",
    guestName: "Pat Wilson",
  },
  {
    id: 1019,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2000, // Direct
    rating: 8,
    publicReview: "Stay was good. Host was responsive.",
    reviewCategory: [{ category: "communication", rating: 10 }],
    submittedAt: "2024-10-09T17:00:00Z",
    guestName: "Dana Moore",
  },
  {
    id: 1020,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    publicReview: "I would stay here again.",
    submittedAt: "2024-10-07T13:45:00Z",
    guestName: "Jessie Clark",
  },
  {
    id: 1021,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview: "Awesome pet-friendly place!",
    submittedAt: "2024-10-05T10:10:00Z",
    guestName: "Alex Johnson",
  },
  {
    id: 1022,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2005, // Bookingcom
    rating: 9,
    submittedAt: "2024-10-03T16:00:00Z",
    guestName: "Sam Smith",
  },
  {
    id: 1023,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2007, // Expedia
    rating: 7,
    publicReview: "The hallway smelled strange, but the room was clean.",
    reviewCategory: [{ category: "cleanliness", rating: 10 }],
    submittedAt: "2024-10-01T12:00:00Z",
    guestName: "Casey Brown",
  },
  {
    id: 1024,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview: "A hidden gem. Great price.",
    submittedAt: "2024-09-29T11:00:00Z",
    guestName: "Jordan Lee",
  },
  {
    id: 1025,
    listingMapId: 102,
    listingName: "Cozy Seattle Studio near Pike Place",
    type: "guest-to-host",
    status: "published",
    channelId: 2022, // Google
    rating: 9,
    publicReview: "Very happy with my stay.",
    submittedAt: "2024-09-27T14:30:00Z",
    guestName: "Morgan White",
  },

  // == Reviews for Listing 103 (5 Reviews) ==
  {
    id: 1026,
    listingMapId: 103,
    listingName: "Sunny Miami Beachfront Condo",
    type: "guest-to-host",
    status: "awaiting",
    channelId: 2002, // Homeaway
    rating: 10,
    publicReview:
      "Absolute paradise. The view is unreal. We will be back every year!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
    ],
    submittedAt: "2024-10-21T09:00:00Z",
    guestName: "Taylor Davis",
  },
  {
    id: 1027,
    listingMapId: 103,
    listingName: "Sunny Miami Beachfront Condo",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview:
      "10/10. The photos do not do it justice. Waking up to the ocean was incredible.",
    submittedAt: "2024-10-18T14:00:00Z",
    guestName: "Chris Miller",
  },
  {
    id: 1028,
    listingMapId: 103,
    listingName: "Sunny Miami Beachfront Condo",
    type: "guest-to-host",
    status: "published",
    channelId: 2000, // Direct
    rating: 9,
    publicReview:
      "Fantastic location. The pool was great. Apartment was clean.",
    submittedAt: "2024-10-15T11:15:00Z",
    guestName: "Pat Wilson",
  },
  {
    id: 1029,
    listingMapId: 103,
    listingName: "Sunny Miami Beachfront Condo",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview: "Perfect family vacation spot.",
    submittedAt: "2024-10-12T10:00:00Z",
    guestName: "Dana Moore",
  },
  {
    id: 1030,
    listingMapId: 103,
    listingName: "Sunny Miami Beachfront Condo",
    type: "guest-to-host",
    status: "published",
    channelId: 2002, // Homeaway
    rating: 10,
    publicReview: "Best rental in Miami.",
    reviewCategory: [{ category: "cleanliness", rating: 10 }],
    submittedAt: "2024-10-09T18:00:00Z",
    guestName: "Jessie Clark",
  },

  // == Reviews for Listing 104 (8 Reviews) ==
  {
    id: 1031,
    listingMapId: 104,
    listingName: "Windy City Views (Chicago)",
    type: "guest-to-host",
    status: "published",
    channelId: 2005, // Bookingcom
    rating: 7,
    publicReview: "It was fine for a business trip. Very basic.",
    submittedAt: "2024-10-19T08:00:00Z",
    guestName: "Alex Johnson",
  },
  {
    id: 1032,
    listingMapId: 104,
    listingName: "Windy City Views (Chicago)",
    type: "guest-to-host",
    status: "awaiting",
    channelId: 2005, // Bookingcom
    rating: 8,
    publicReview: "Good location near the train. Clean and safe.",
    reviewCategory: [{ category: "cleanliness", rating: 10 }],
    submittedAt: "2024-10-16T17:00:00Z",
    guestName: "Sam Smith",
  },
  {
    id: 1033,
    listingMapId: 104,
    listingName: "Windy City Views (Chicago)",
    type: "guest-to-host",
    status: "published",
    channelId: 2022, // Google
    rating: 5,
    publicReview:
      "The pictures were misleading. Much smaller than expected and the 'view' was of a brick wall.",
    submittedAt: "2024-10-14T12:30:00Z",
    guestName: "Casey Brown",
  },
  {
    id: 1034,
    listingMapId: 104,
    listingName: "Windy City Views (Chicago)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    publicReview: "No complaints. Easy check-in, clean room.",
    submittedAt: "2024-10-11T16:00:00Z",
    guestName: "Jordan Lee",
  },
  {
    id: 1035,
    listingMapId: 104,
    listingName: "Windy City Views (Chicago)",
    type: "guest-to-host",
    status: "published",
    channelId: 2005, // Bookingcom
    rating: 6,
    publicReview: "The Wi-Fi was very slow. Had to use my hotspot for work.",
    reviewCategory: [{ category: "communication", rating: 10 }],
    submittedAt: "2024-10-08T09:45:00Z",
    guestName: "Morgan White",
  },
  {
    id: 1036,
    listingMapId: 104,
    listingName: "Windy City Views (Chicago)",
    type: "guest-to-host",
    status: "awaiting",
    channelId: 2007, // Expedia
    rating: 8,
    publicReview: "Decent place to sleep. Good price.",
    submittedAt: "2024-10-05T13:00:00Z",
    guestName: "Taylor Davis",
  },
  {
    id: 1037,
    listingMapId: 104,
    listingName: "Windy City Views (Chicago)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    publicReview: "Great crash pad. Good communication from host.",
    submittedAt: "2024-10-02T10:20:00Z",
    guestName: "Chris Miller",
  },
  {
    id: 1038,
    listingMapId: 104,
    listingName: "Windy City Views (Chicago)",
    type: "guest-to-host",
    status: "published",
    channelId: 2005, // Bookingcom
    rating: 8,
    submittedAt: "2024-09-30T19:00:00Z",
    guestName: "Pat Wilson",
  },

  // == Reviews for Listing 105 (12 Reviews) ==
  {
    id: 1039,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2002, // Homeaway
    rating: 10,
    publicReview:
      "The hot tub was amazing after a long day of hiking! Beautiful place.",
    reviewCategory: [{ category: "cleanliness", rating: 10 }],
    submittedAt: "2024-10-22T11:00:00Z",
    guestName: "Dana Moore",
  },
  {
    id: 1040,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    publicReview: "Cozy and rustic. We loved the fireplace.",
    submittedAt: "2024-10-20T14:30:00Z",
    guestName: "Jessie Clark",
  },
  {
    id: 1041,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    publicReview: "Great basecamp for exploring the Rockies.",
    submittedAt: "2024-10-18T12:00:00Z",
    guestName: "Alex Johnson",
  },
  {
    id: 1042,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2000, // Direct
    rating: 10,
    publicReview: "Perfect. Just perfect.",
    submittedAt: "2024-10-17T09:10:00Z",
    guestName: "Sam Smith",
  },
  {
    id: 1043,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2002, // Homeaway
    rating: 8,
    publicReview: "The dog loved the yard. Great pet-friendly option.",
    submittedAt: "2024-10-15T10:00:00Z",
    guestName: "Casey Brown",
  },
  {
    id: 1044,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    publicReview: "Very clean and well-stocked kitchen.",
    reviewCategory: [{ category: "cleanliness", rating: 10 }],
    submittedAt: "2024-10-13T16:00:00Z",
    guestName: "Jordan Lee",
  },
  {
    id: 1045,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2022, // Google
    rating: 10,
    submittedAt: "2024-10-11T11:45:00Z",
    guestName: "Morgan White",
  },
  {
    id: 1046,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 10,
    publicReview: "Host was very communicative and helpful.",
    reviewCategory: [{ category: "communication", rating: 10 }],
    submittedAt: "2024-10-09T13:00:00Z",
    guestName: "Taylor Davis",
  },
  {
    id: 1047,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2002, // Homeaway
    rating: 7,
    publicReview: "A bit farther from the ski lifts than we thought, but nice.",
    submittedAt: "2024-10-07T15:00:00Z",
    guestName: "Chris Miller",
  },
  {
    id: 1048,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    publicReview: "Cozy and quiet. We'd come back.",
    submittedAt: "2024-10-04T10:00:00Z",
    guestName: "Pat Wilson",
  },
  {
    id: 1049,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2022, // Google
    rating: 10,
    publicReview: "Five stars!",
    submittedAt: "2024-10-02T19:30:00Z",
    guestName: "Dana Moore",
  },
  {
    id: 1050,
    listingMapId: 105,
    listingName: "Rocky Mountain Getaway (Denver)",
    type: "guest-to-host",
    status: "published",
    channelId: 2000, // Direct
    rating: 9,
    submittedAt: "2024-09-30T12:00:00Z",
    guestName: "Jessie Clark",
  },

  // == Reviews for Listing 106 (2 Reviews) ==
  {
    id: 1051,
    listingMapId: 106,
    listingName: "Historic Boston Common Apartment",
    type: "guest-to-host",
    status: "published",
    channelId: 2018, // AirbnbOfficial
    rating: 9,
    publicReview:
      "Incredible location. The apartment is old but has character. Very clean.",
    reviewCategory: [{ category: "cleanliness", rating: 10 }],
    submittedAt: "2024-10-14T15:00:00Z",
    guestName: "Alex Johnson",
  },
  {
    id: 1052,
    listingMapId: 106,
    listingName: "Historic Boston Common Apartment",
    type: "guest-to-host",
    status: "published",
    channelId: 2000, // Direct
    rating: 8,
    publicReview:
      "You can't beat the location, right on the park. The apartment itself is very simple, but fine for a short stay.",
    submittedAt: "2024-10-10T11:00:00Z",
    guestName: "Sam Smith",
  },
];
