### Fetch listings
GET http://localhost:3000/listings

### Fetch 1 listings
GET http://localhost:3000/listings/101

### Fetch reviews
GET http://localhost:3000/reviews
# Authorization: Bearer admin

### Fetch 1 review
GET http://localhost:3000/reviews/1040

### Change review status
PATCH http://localhost:3000/reviews/1040?status=published
Authorization: Bearer admin